#!/usr/bin/env python3
"""Build SQL seed from Markdown template files.

Usage:
    python backend/seeds/build_template_seed.py [--out PATH] [--dry-run]

Reads all backend/seeds/templates/{lang}/tpl-*.md files, parses their
YAML front matter, computes SHA-256 hashes, and emits an idempotent SQL
upsert that can be applied to the document_templates and
document_template_versions tables.

Output: backend/seeds/document_templates_seed.sql (overwrite)
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml  # PyYAML
except ImportError:
    print("ERROR: PyYAML required — pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ── Config ─────────────────────────────────────────────────────────────────────

SEEDS_DIR = Path(__file__).parent
TEMPLATES_DIR = SEEDS_DIR / "templates"
DEFAULT_OUT = SEEDS_DIR / "document_templates_seed.sql"
MANIFEST_PATH = SEEDS_DIR / "template_manifest.json"

LANGUAGES = ["es", "en", "ca", "fr", "de", "it", "pt", "nl", "sv", "da", "no"]
CANONICAL_LANG = "es"

# ── Helpers ────────────────────────────────────────────────────────────────────

_FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_PLACEHOLDER_RE = re.compile(r"\{\{([a-z][a-z0-9_.]*)\}\}")


def parse_front_matter(content: str) -> tuple[dict, str]:
    m = _FRONT_MATTER_RE.match(content)
    if not m:
        return {}, content
    fm = yaml.safe_load(m.group(1)) or {}
    body = content[m.end():]
    return fm, body


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def extract_placeholders(body: str) -> list[str]:
    return sorted(set(_PLACEHOLDER_RE.findall(body)))


def sql_str(value: str | None) -> str:
    if value is None:
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def sql_array(items: list[str]) -> str:
    if not items:
        return "ARRAY[]::text[]"
    elems = ", ".join(sql_str(i) for i in items)
    return f"ARRAY[{elems}]"


def sql_json(obj: dict | list | None) -> str:
    if obj is None:
        return "NULL"
    return sql_str(json.dumps(obj, ensure_ascii=False))


# ── Core logic ─────────────────────────────────────────────────────────────────

def scan_templates() -> list[dict]:
    """Scan all template Markdown files and return parsed metadata."""
    records = []
    for lang in LANGUAGES:
        lang_dir = TEMPLATES_DIR / lang
        if not lang_dir.exists():
            continue
        for md_file in sorted(lang_dir.glob("tpl-*.md")):
            content = md_file.read_text(encoding="utf-8")
            fm, body = parse_front_matter(content)
            placeholders = extract_placeholders(body)
            content_hash = sha256_hex(content)

            template_key = fm.get("template_key") or md_file.stem
            records.append({
                "file": md_file,
                "template_key": template_key,
                "language": fm.get("language") or lang,
                "document_type": fm.get("document_type") or fm.get("template_document_type") or "generico",
                "name": fm.get("name") or fm.get("title") or template_key.replace("-", " ").title(),
                "jurisdiction": fm.get("jurisdiction") or "España",
                "ape_codes": fm.get("ape_codes") or [],
                "version": fm.get("version") or "1.0",
                "legal_basis": fm.get("legal_basis"),
                "description": fm.get("description"),
                "placeholders": placeholders,
                "content_hash": content_hash,
                "body": body,
                "full_content": content,
                "is_canonical": (fm.get("language") or lang) == CANONICAL_LANG,
            })
    return records


def build_sql(records: list[dict]) -> str:
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "-- Auto-generated by build_template_seed.py",
        f"-- Generated at: {now}",
        "-- DO NOT EDIT MANUALLY — re-run the script to regenerate",
        "",
        "BEGIN;",
        "",
    ]

    # Group by template_key to get canonical (ES) version as the main template
    by_key: dict[str, list[dict]] = {}
    for r in records:
        by_key.setdefault(r["template_key"], []).append(r)

    for key, variants in sorted(by_key.items()):
        canonical = next((v for v in variants if v["language"] == CANONICAL_LANG), variants[0])

        # Upsert document_templates row (canonical)
        lines += [
            f"-- Template family: {key}",
            "INSERT INTO document_templates (",
            "  template_key, name, template_document_type, jurisdiction,",
            "  language, ape_codes, status, system_template, description, created_at, updated_at",
            ") VALUES (",
            f"  {sql_str(key)},",
            f"  {sql_str(canonical['name'])},",
            f"  {sql_str(canonical['document_type'])},",
            f"  {sql_str(canonical['jurisdiction'])},",
            f"  {sql_str(canonical['language'])},",
            f"  {sql_array(canonical['ape_codes'])},",
            "  'draft',",
            "  TRUE,",
            f"  {sql_str(canonical['description'])},",
            f"  '{now}', '{now}'",
            ") ON CONFLICT (template_key) DO UPDATE SET",
            f"  name = EXCLUDED.name,",
            f"  template_document_type = EXCLUDED.template_document_type,",
            f"  updated_at = '{now}';",
            "",
        ]

        # Upsert a template version for each language variant
        for variant in sorted(variants, key=lambda v: v["language"]):
            lines += [
                "INSERT INTO document_template_versions (",
                "  template_id, version_number, language, content_md5,",
                "  content_storage_path, placeholders, ape_codes,",
                "  validation_status, change_summary, is_canonical,",
                "  created_at, updated_at",
                ") SELECT",
                f"  id,",
                f"  1,",
                f"  {sql_str(variant['language'])},",
                f"  {sql_str(variant['content_hash'])},",
                f"  {sql_str(f'templates/{variant[\"language\"]}/{variant[\"file\"].name}')},",
                f"  {sql_array(variant['placeholders'])},",
                f"  {sql_array(variant['ape_codes'])},",
                "  'pending',",
                f"  {sql_str(f'Initial seed — {variant[\"version\"]}')},",
                f"  {str(variant['is_canonical']).upper()},",
                f"  '{now}', '{now}'",
                f"FROM document_templates WHERE template_key = {sql_str(key)}",
                "ON CONFLICT (template_id, version_number, language) DO NOTHING;",
                "",
            ]

    lines += ["COMMIT;", ""]
    return "\n".join(lines)


def build_manifest(records: list[dict]) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total": len(records),
        "languages": LANGUAGES,
        "templates": [
            {
                "template_key": r["template_key"],
                "language": r["language"],
                "document_type": r["document_type"],
                "name": r["name"],
                "content_hash": r["content_hash"],
                "placeholders": r["placeholders"],
                "placeholder_count": len(r["placeholders"]),
                "file": str(r["file"].relative_to(SEEDS_DIR)),
            }
            for r in records
        ],
    }


# ── CLI ────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output SQL path")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Output manifest JSON path")
    parser.add_argument("--dry-run", action="store_true", help="Print SQL to stdout, do not write files")
    parser.add_argument("--lang", help="Only process this language (e.g. es)")
    args = parser.parse_args()

    if args.lang:
        global LANGUAGES
        LANGUAGES = [args.lang]

    print(f"Scanning templates in {TEMPLATES_DIR} ...")
    records = scan_templates()
    print(f"Found {len(records)} template variants")

    if not records:
        print("ERROR: No templates found. Check TEMPLATES_DIR.", file=sys.stderr)
        sys.exit(1)

    sql = build_sql(records)
    manifest = build_manifest(records)

    if args.dry_run:
        print("\n--- SQL output ---")
        print(sql[:2000], "..." if len(sql) > 2000 else "")
        print(f"\n--- Manifest: {len(records)} records ---")
        by_lang = {}
        for r in records:
            by_lang.setdefault(r["language"], 0)
            by_lang[r["language"]] += 1
        for lang, count in sorted(by_lang.items()):
            print(f"  {lang}: {count} templates")
        return

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sql, encoding="utf-8")
    print(f"SQL written to: {out_path}")

    manifest_path = Path(args.manifest)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Manifest written to: {manifest_path}")

    # Summary
    by_lang: dict[str, int] = {}
    for r in records:
        by_lang[r["language"]] = by_lang.get(r["language"], 0) + 1
    print("\nVariants per language:")
    for lang, count in sorted(by_lang.items()):
        print(f"  {lang}: {count}")
    total = sum(by_lang.values())
    print(f"\nTotal: {total} variants across {len(by_lang)} languages")


if __name__ == "__main__":
    main()
