-- Migration 037: Nexus Sellers — Motor de Adquisición de Vendedores
-- Tracks discovered seller prospects (FSBOs, stagnant listings, STR enforcement victims)
-- before they appear on the open market. Core of the seller-side prospecting engine.

CREATE TABLE IF NOT EXISTS nexus_sellers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Seller identity
    nombre_propietario TEXT,
    empresa TEXT,

    -- Property location
    website_url TEXT,
    anuncio_url TEXT,
    direccion TEXT,
    zona TEXT NOT NULL CHECK (zona IN (
        'andratx', 'calvia', 'son_ferrer', 'santa_ponca',
        'paguera', 'portals_nous', 'bendinat', 'punta_negra',
        'costa_den_blanes', 'port_adriano', 'palma', 'otra'
    )),

    -- Detection source
    fuente TEXT NOT NULL CHECK (fuente IN (
        'idealista',            -- Detected via Idealista scraping
        'fotocasa',             -- Detected via Fotocasa (FSBO signals)
        'fsbo',                 -- For Sale By Owner explicitly
        'str_enforcement',      -- STR license loss signal
        'prospection_match',    -- Generated by prospection_weekly skill
        'manual',               -- Manually added by Toni
        'referral',             -- Referral from network
        'scraping'              -- Generic web scraping
    )),

    -- Property data
    precio_publicado NUMERIC(12, 2),
    precio_estimado NUMERIC(12, 2),        -- AI estimated value for negotiation
    superficie_m2 NUMERIC(8, 2),
    tipo_propiedad TEXT,                    -- villa, apartamento, finca, solar
    dias_en_mercado INTEGER,               -- Days on market at detection time
    datos_extraidos JSONB DEFAULT '{}',    -- Raw scraped data (JSON)

    -- Pipeline state
    estado_contacto TEXT NOT NULL DEFAULT 'sin_contacto' CHECK (estado_contacto IN (
        'sin_contacto',         -- Detected, not yet contacted
        'primer_contacto',      -- First outreach sent
        'en_seguimiento',       -- Ongoing follow-up
        'reunion_agendada',     -- Meeting scheduled
        'propuesta_enviada',    -- Exclusive mandate proposal sent
        'mandato_exclusivo',    -- SUCCESS: exclusive mandate signed
        'descartado'            -- Discarded (not interested, wrong profile)
    )),

    -- Priority scoring (1=low, 5=Whale)
    prioridad INTEGER NOT NULL DEFAULT 3 CHECK (prioridad BETWEEN 1 AND 5),

    -- AI-generated intelligence
    notas TEXT,
    argumentario TEXT,                     -- AI-generated captation pitch
    senales_motivacion JSONB DEFAULT '[]', -- Detected motivation signals

    -- NotebookLM private notebook (Phase 4 — per-seller whale audit)
    notebooklm_notebook_id TEXT,          -- Private NLM notebook ID for this seller

    -- Timeline
    fecha_deteccion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_primer_contacto TIMESTAMPTZ,
    fecha_ultimo_contacto TIMESTAMPTZ,
    fecha_mandato TIMESTAMPTZ,            -- When exclusive was signed

    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_nexus_sellers_org_zona
    ON nexus_sellers(org_id, zona);

CREATE INDEX IF NOT EXISTS idx_nexus_sellers_org_estado
    ON nexus_sellers(org_id, estado_contacto);

CREATE INDEX IF NOT EXISTS idx_nexus_sellers_org_prioridad
    ON nexus_sellers(org_id, prioridad DESC);

CREATE INDEX IF NOT EXISTS idx_nexus_sellers_fuente
    ON nexus_sellers(org_id, fuente);

CREATE INDEX IF NOT EXISTS idx_nexus_sellers_deteccion
    ON nexus_sellers(fecha_deteccion DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_nexus_sellers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER nexus_sellers_updated_at
    BEFORE UPDATE ON nexus_sellers
    FOR EACH ROW
    EXECUTE FUNCTION update_nexus_sellers_updated_at();

-- Row Level Security
ALTER TABLE nexus_sellers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_isolation_nexus_sellers"
    ON nexus_sellers
    USING (org_id = current_setting('app.org_id', true)::UUID);

-- Comments
COMMENT ON TABLE nexus_sellers IS
    'Seller prospects detected before they appear on the open market. '
    'Fed by scraping (Idealista/Fotocasa), STR enforcement signals, '
    'and the prospection_weekly skill. Core of the seller-side prospecting engine.';

COMMENT ON COLUMN nexus_sellers.prioridad IS
    '1=cold/low, 2=follow-up, 3=potential, 4=high-value, 5=Whale (respond <15min)';

COMMENT ON COLUMN nexus_sellers.notebooklm_notebook_id IS
    'Phase 4: For Whale sellers, a private NotebookLM notebook is created '
    'with their listing data for deep competitive intelligence analysis.';
